### ISSUE TITLE
Is there any source code for the streamlit component of this project? 

### ISSUE THREAD

**Issue by geo7** [sTechLab/VoterFraud2020#2]
I found this from this page: https://streamlit.io/gallery?category=data-visualization , but can't see anything relating to streamlit within this repo. 

Is the source for that anywhere?

**Comment by anton164** [comment]
Yes, the complete source code is available here: https://github.com/sTechLab/VoterFraud2020-analysis/tree/main/interface

The app entrypoint is here:
https://github.com/sTechLab/VoterFraud2020-analysis/blob/main/app.py

Feel free to reach out if you have any further questions
